//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name ExtractAllStudentsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExtractAllStudents", ReplyAction="*")]
        WebClient.ServiceReference1.ExtractAllStudentsResponse ExtractAllStudents(WebClient.ServiceReference1.ExtractAllStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExtractAllStudents", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.ExtractAllStudentsResponse> ExtractAllStudentsAsync(WebClient.ServiceReference1.ExtractAllStudentsRequest request);
        
        // CODEGEN: Generating message contract since element name ExtractSomePartsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExtractSomeParts", ReplyAction="*")]
        WebClient.ServiceReference1.ExtractSomePartsResponse ExtractSomeParts(WebClient.ServiceReference1.ExtractSomePartsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExtractSomeParts", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.ExtractSomePartsResponse> ExtractSomePartsAsync(WebClient.ServiceReference1.ExtractSomePartsRequest request);
        
        // CODEGEN: Generating message contract since element name ExtractDetailInformationResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExtractDetailInformation", ReplyAction="*")]
        WebClient.ServiceReference1.ExtractDetailInformationResponse ExtractDetailInformation(WebClient.ServiceReference1.ExtractDetailInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExtractDetailInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.ExtractDetailInformationResponse> ExtractDetailInformationAsync(WebClient.ServiceReference1.ExtractDetailInformationRequest request);
        
        // CODEGEN: Generating message contract since element name ReturnAllResultsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnAllResults", ReplyAction="*")]
        WebClient.ServiceReference1.ReturnAllResultsResponse ReturnAllResults(WebClient.ServiceReference1.ReturnAllResultsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnAllResults", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.ReturnAllResultsResponse> ReturnAllResultsAsync(WebClient.ServiceReference1.ReturnAllResultsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExtractAllStudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExtractAllStudents", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.ExtractAllStudentsRequestBody Body;
        
        public ExtractAllStudentsRequest() {
        }
        
        public ExtractAllStudentsRequest(WebClient.ServiceReference1.ExtractAllStudentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ExtractAllStudentsRequestBody {
        
        public ExtractAllStudentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExtractAllStudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExtractAllStudentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.ExtractAllStudentsResponseBody Body;
        
        public ExtractAllStudentsResponse() {
        }
        
        public ExtractAllStudentsResponse(WebClient.ServiceReference1.ExtractAllStudentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExtractAllStudentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExtractAllStudentsResult;
        
        public ExtractAllStudentsResponseBody() {
        }
        
        public ExtractAllStudentsResponseBody(string ExtractAllStudentsResult) {
            this.ExtractAllStudentsResult = ExtractAllStudentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExtractSomePartsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExtractSomeParts", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.ExtractSomePartsRequestBody Body;
        
        public ExtractSomePartsRequest() {
        }
        
        public ExtractSomePartsRequest(WebClient.ServiceReference1.ExtractSomePartsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ExtractSomePartsRequestBody {
        
        public ExtractSomePartsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExtractSomePartsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExtractSomePartsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.ExtractSomePartsResponseBody Body;
        
        public ExtractSomePartsResponse() {
        }
        
        public ExtractSomePartsResponse(WebClient.ServiceReference1.ExtractSomePartsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExtractSomePartsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExtractSomePartsResult;
        
        public ExtractSomePartsResponseBody() {
        }
        
        public ExtractSomePartsResponseBody(string ExtractSomePartsResult) {
            this.ExtractSomePartsResult = ExtractSomePartsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExtractDetailInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExtractDetailInformation", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.ExtractDetailInformationRequestBody Body;
        
        public ExtractDetailInformationRequest() {
        }
        
        public ExtractDetailInformationRequest(WebClient.ServiceReference1.ExtractDetailInformationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ExtractDetailInformationRequestBody {
        
        public ExtractDetailInformationRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExtractDetailInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExtractDetailInformationResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.ExtractDetailInformationResponseBody Body;
        
        public ExtractDetailInformationResponse() {
        }
        
        public ExtractDetailInformationResponse(WebClient.ServiceReference1.ExtractDetailInformationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExtractDetailInformationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExtractDetailInformationResult;
        
        public ExtractDetailInformationResponseBody() {
        }
        
        public ExtractDetailInformationResponseBody(string ExtractDetailInformationResult) {
            this.ExtractDetailInformationResult = ExtractDetailInformationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnAllResultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnAllResults", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.ReturnAllResultsRequestBody Body;
        
        public ReturnAllResultsRequest() {
        }
        
        public ReturnAllResultsRequest(WebClient.ServiceReference1.ReturnAllResultsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReturnAllResultsRequestBody {
        
        public ReturnAllResultsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnAllResultsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnAllResultsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebClient.ServiceReference1.ReturnAllResultsResponseBody Body;
        
        public ReturnAllResultsResponse() {
        }
        
        public ReturnAllResultsResponse(WebClient.ServiceReference1.ReturnAllResultsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnAllResultsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebClient.ServiceReference1.ArrayOfString ReturnAllResultsResult;
        
        public ReturnAllResultsResponseBody() {
        }
        
        public ReturnAllResultsResponseBody(WebClient.ServiceReference1.ArrayOfString ReturnAllResultsResult) {
            this.ReturnAllResultsResult = ReturnAllResultsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebClient.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebClient.ServiceReference1.WebService1Soap>, WebClient.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.ExtractAllStudentsResponse WebClient.ServiceReference1.WebService1Soap.ExtractAllStudents(WebClient.ServiceReference1.ExtractAllStudentsRequest request) {
            return base.Channel.ExtractAllStudents(request);
        }
        
        public string ExtractAllStudents() {
            WebClient.ServiceReference1.ExtractAllStudentsRequest inValue = new WebClient.ServiceReference1.ExtractAllStudentsRequest();
            inValue.Body = new WebClient.ServiceReference1.ExtractAllStudentsRequestBody();
            WebClient.ServiceReference1.ExtractAllStudentsResponse retVal = ((WebClient.ServiceReference1.WebService1Soap)(this)).ExtractAllStudents(inValue);
            return retVal.Body.ExtractAllStudentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.ExtractAllStudentsResponse> WebClient.ServiceReference1.WebService1Soap.ExtractAllStudentsAsync(WebClient.ServiceReference1.ExtractAllStudentsRequest request) {
            return base.Channel.ExtractAllStudentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.ExtractAllStudentsResponse> ExtractAllStudentsAsync() {
            WebClient.ServiceReference1.ExtractAllStudentsRequest inValue = new WebClient.ServiceReference1.ExtractAllStudentsRequest();
            inValue.Body = new WebClient.ServiceReference1.ExtractAllStudentsRequestBody();
            return ((WebClient.ServiceReference1.WebService1Soap)(this)).ExtractAllStudentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.ExtractSomePartsResponse WebClient.ServiceReference1.WebService1Soap.ExtractSomeParts(WebClient.ServiceReference1.ExtractSomePartsRequest request) {
            return base.Channel.ExtractSomeParts(request);
        }
        
        public string ExtractSomeParts() {
            WebClient.ServiceReference1.ExtractSomePartsRequest inValue = new WebClient.ServiceReference1.ExtractSomePartsRequest();
            inValue.Body = new WebClient.ServiceReference1.ExtractSomePartsRequestBody();
            WebClient.ServiceReference1.ExtractSomePartsResponse retVal = ((WebClient.ServiceReference1.WebService1Soap)(this)).ExtractSomeParts(inValue);
            return retVal.Body.ExtractSomePartsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.ExtractSomePartsResponse> WebClient.ServiceReference1.WebService1Soap.ExtractSomePartsAsync(WebClient.ServiceReference1.ExtractSomePartsRequest request) {
            return base.Channel.ExtractSomePartsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.ExtractSomePartsResponse> ExtractSomePartsAsync() {
            WebClient.ServiceReference1.ExtractSomePartsRequest inValue = new WebClient.ServiceReference1.ExtractSomePartsRequest();
            inValue.Body = new WebClient.ServiceReference1.ExtractSomePartsRequestBody();
            return ((WebClient.ServiceReference1.WebService1Soap)(this)).ExtractSomePartsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.ExtractDetailInformationResponse WebClient.ServiceReference1.WebService1Soap.ExtractDetailInformation(WebClient.ServiceReference1.ExtractDetailInformationRequest request) {
            return base.Channel.ExtractDetailInformation(request);
        }
        
        public string ExtractDetailInformation() {
            WebClient.ServiceReference1.ExtractDetailInformationRequest inValue = new WebClient.ServiceReference1.ExtractDetailInformationRequest();
            inValue.Body = new WebClient.ServiceReference1.ExtractDetailInformationRequestBody();
            WebClient.ServiceReference1.ExtractDetailInformationResponse retVal = ((WebClient.ServiceReference1.WebService1Soap)(this)).ExtractDetailInformation(inValue);
            return retVal.Body.ExtractDetailInformationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.ExtractDetailInformationResponse> WebClient.ServiceReference1.WebService1Soap.ExtractDetailInformationAsync(WebClient.ServiceReference1.ExtractDetailInformationRequest request) {
            return base.Channel.ExtractDetailInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.ExtractDetailInformationResponse> ExtractDetailInformationAsync() {
            WebClient.ServiceReference1.ExtractDetailInformationRequest inValue = new WebClient.ServiceReference1.ExtractDetailInformationRequest();
            inValue.Body = new WebClient.ServiceReference1.ExtractDetailInformationRequestBody();
            return ((WebClient.ServiceReference1.WebService1Soap)(this)).ExtractDetailInformationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceReference1.ReturnAllResultsResponse WebClient.ServiceReference1.WebService1Soap.ReturnAllResults(WebClient.ServiceReference1.ReturnAllResultsRequest request) {
            return base.Channel.ReturnAllResults(request);
        }
        
        public WebClient.ServiceReference1.ArrayOfString ReturnAllResults() {
            WebClient.ServiceReference1.ReturnAllResultsRequest inValue = new WebClient.ServiceReference1.ReturnAllResultsRequest();
            inValue.Body = new WebClient.ServiceReference1.ReturnAllResultsRequestBody();
            WebClient.ServiceReference1.ReturnAllResultsResponse retVal = ((WebClient.ServiceReference1.WebService1Soap)(this)).ReturnAllResults(inValue);
            return retVal.Body.ReturnAllResultsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceReference1.ReturnAllResultsResponse> WebClient.ServiceReference1.WebService1Soap.ReturnAllResultsAsync(WebClient.ServiceReference1.ReturnAllResultsRequest request) {
            return base.Channel.ReturnAllResultsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceReference1.ReturnAllResultsResponse> ReturnAllResultsAsync() {
            WebClient.ServiceReference1.ReturnAllResultsRequest inValue = new WebClient.ServiceReference1.ReturnAllResultsRequest();
            inValue.Body = new WebClient.ServiceReference1.ReturnAllResultsRequestBody();
            return ((WebClient.ServiceReference1.WebService1Soap)(this)).ReturnAllResultsAsync(inValue);
        }
    }
}
